### ISSUE TITLE
Usage examples

### ISSUE THREAD

**Issue by mfeckie** [oceanpkg/rosy#5]
I can across this library when looking for ways to interact with Rust from Ruby.

Look interesting, but I can't seem to find any examples of it in action.

Are there any blog posts or examples I could look at?

**Comment by kubo** [comment]
@mfeckie 
I created a cargo subcommand to create a ruby extension written by rust.
See https://github.com/kubo/cargo-rbext
`cargo rbext new --lib xxx` creates `xxx/src/lib.rs`, which defines a Ruby class with an instance method and a class method.
